Update npm-publish-github-packages.yml

diff --git a/.github/workflows/npm-publish-github-packages.yml b/.github/workflows/npm-publish-github-packages.yml
--- a/.github/workflows/npm-publish-github-packages.yml
+++ b/.github/workflows/npm-publish-github-packages.yml
@@ -29,8 +29,12 @@ jobs:
       run: |
         echo "$ENV_CONTENTS" > backend/.env
         pwd
-        scp -v -r ./backend/ memighty-test-server@192.168.29.120:/var/www/
-        echo "Backend deployment completed"
+        echo "Starting SCP transfer with verbose output"
+        scp -vvv -r ./eums_backend/ memighty-test-server@192.168.29.120:/var/www/
+        if [ $? -ne 0 ]; then
+          echo "SCP command failed"
+          exit 1
+        fi
 
     - name: Install and Start Backend
       uses: appleboy/ssh-action@v1.0.3
